//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAdministrationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public int AccountId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountTitle { get; set; }
        public string CustomerName { get; set; }
        public string AccountType { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string PostalAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string NICNumber { get; set; }
        public string EmailAddress { get; set; }
        public string CompanyName { get; set; }
        public string Occupation { get; set; }
        public int Balance { get; set; }
        public byte[] ProfilePicture { get; set; }
        public byte[] Signature { get; set; }
    }
}
